server:
  port: 8080

spring:
  datasource:
    # По умолчанию postgresql имеет 5432 порт. Но так как подразумевается запуск через docker-compose, указан порт
    # из docker-compose.yaml для корректной проброски. Если у вас локально установлен postgresql и вы собираетесь
    # использовать его, то требуется поменить его на нужный
    url: jdbc:postgresql://localhost:5432/db_wallet
    #Имя пользователя БД
    username: postgres
    password: sahara202020
  flyway:
    #Вкл/выкл flyway
    enabled: true
    #Расположение файлов миграции
    locations:
      - db.migration
    default-schema: db_wallet
  jpa:
    properties:
      hibernate:
        default_schema: db_wallet
        format_sql: true
    show-sql: true
    hibernate:
      #Генерация схемы БД на основе Entity
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  swagger-ui:
    enabled: true
  show-login-endpoint: true
